<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\CollectionHistory;

/**
 * CollectionHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(CollectionHistory $collectionHistory)
    {
        $em = $this->getEntityManager();
        // persist the new contact in the database
        $em->persist($collectionHistory);
        // flush them to the database
        $em->flush();
        //Close the entity manager
        // return the id of the new contact in the database
        return $collectionHistory->getId();
    }

    public function remove(CollectionHistory $collectionHistory)
    {
        $em = $this->getEntityManager();
        // persist the new contact in the database
        $em->remove($collectionHistory);
        // flush them to the database
        $em->flush();
        //Close the entity manager
    }
}
