<?php

namespace AppBundle\Repository;

/**
 * CollectionHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
