<?php

namespace AppBundle\Repository;

/**
 * ContactPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
