<?php

namespace AppBundle\Repository;

/**
 * EduMatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EduMatRepository extends \Doctrine\ORM\EntityRepository
{

}
