<?php
namespace AppBundle\Repository;

use AppBundle\Entity\EduMat;
/**
 * EduMatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EduMatRepository extends \Doctrine\ORM\EntityRepository
{

    // SO FAR THIS REPOSITY IS UNUSED. THE FUNCTIONALITY HAS BEEN MOVED INTO THE CONTROLLER


    public function insert(EduMat $edu)
    {
        //$em = $this->getEntityManager();
        //$em->persist($edu);
        //$em->flush();

        //$em->close();
        //$em = null;

        //return $edu->getId();
    }
}
