<?php

namespace AppBundle\Repository;

/**
 * OOPsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OOPsRepository extends \Doctrine\ORM\EntityRepository
{
}
