<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository; 
use AppBundle\Entity\OOPs;

/**
 * OOPsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OOPsRepository extends EntityRepository
{
    /**
     * inserts an OOPs object to the database oops table
     * @param OOPs $oops 
     * @return string
     */
    public function insert(OOPs $oops)
    {
        $em = $this->getEntityManager(); 
        $em->persist($oops); 
        $em->flush(); 
        $em->close(); 
        return $oops->getId();
    }
}
