<?php

namespace AppBundle\Repository;

/**
 * PickupInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PickupInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
