<?php

namespace AppBundle\Repository;

/**
 * RoutePickupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoutePickupRepository extends \Doctrine\ORM\EntityRepository
{
}
