<?php

namespace AppBundle\Repository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\Route;
class RouteRepository extends \Doctrine\ORM\EntityRepository
{

    public function save(Route $route){

    }
}
