<?php

namespace AppBundle\Repository;

/**
 * RouteCSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteCSVRepository extends \Doctrine\ORM\EntityRepository
{
}
