<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Truck;
use AppBundle\Services\SearchHelper;

/**
 * TruckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TruckRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Story40a
     * returns all (if null), returns from search if not null
     * @param mixed $queryStrings an array of strings to query the database on
     * @return array of searched entites returned from the queries
     */
    public function truckFilter($filters=null)
    {
        $trucks = array();

        if(is_null($filters))
        {
            $trucks = $this->getEntityManager()
                ->getRepository(Truck::class)->findAll();
        }
        else
        {
            rsort( $filters );
            if(isset( $filters[0] ) && is_array( $filters[0])) //if 2d array(from POST Request)
            {
                $filters = $filters['filter_list'];
            }

            $trucks = $this->getEntityManager()
                ->getRepository(Truck::class)->truckSearch($filters, array("id"), "truckId");
        }

        return $trucks;
    }


    /**
     * Story 40a
     * Search through the database and check if any records contain any of
     *  the passed in strings (array of strings) in any of their fields.
     * @param mixed $queryStrings an array of strings to query the database on
     * @return array of searched entites returned from the queries
     */
    public function truckSearch($queryStrings, $excludedProperties = array(), $sortOnProperty = null, $sortDirection = "DESC")
    {
        // get the field names of the Truck entity
        $truckClassProperties = $this->getClassMetadata(Truck::class)->fieldNames;

        //an array of abbreviations to be used in the query. These represent each join
        $classNames = array('t');


        foreach ($excludedProperties as $excludedProperty)
        {
            if(in_array($excludedProperty, $truckClassProperties))
            {
                $truckClassProperties = array_diff($truckClassProperties, $excludedProperties);
            }
        }

        $classPropertiesArray = array($truckClassProperties);

        //create a searchHelper instance
        $searchHelper = new SearchHelper();

        //call the searchHelper service to return the class properties string
        $classPropertiesString = $searchHelper->searchHelper($classPropertiesArray, $queryStrings, $classNames);

        $sortString="";
        if(!is_null($sortOnProperty))
        {
            $sortString = " ORDER BY $classNames[0].$sortOnProperty $sortDirection";
        }

        // query db
        $records = $this->getEntityManager()->createQuery(
        "SELECT t FROM AppBundle:Truck t
        WHERE $classPropertiesString
        $sortString"
        )->getResult();

        // remove any NULL values from the array (NULL values are represented by non-propety objects)
        $records = array_filter($records);

        $truckObjects = array();

        foreach ($records as $record)
        {
        	if(get_class($record) == "AppBundle\Entity\Truck")
            {
                $truckObjects[] = $record;
            }
        }

        return $truckObjects;
    }
}