<?php

namespace AppBundle\Repository;

/**
 * TruckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TruckRepository extends \Doctrine\ORM\EntityRepository
{
    // Save

    // Delete

    // Get All

    // Get One
}
