# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_control:
        #the higher a rule is in this list, the more affinity it takes
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #no role specified means no roles allowed
        - { path: ^/forbidden }
        - { path: ^/, roles: ROLE_ADMIN }

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            ##DEFAULT
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: db_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login: 
                login_path: login
                check_path: login

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt